CREATE DATABASE QUANLYDOANHTHU;
DROP DATABASE QUANLYDOANHTHU;
CREATE TABLE KHACHHANG(
	MAKH VARCHAR(8) NOT NULL PRIMARY KEY,
	TENKH NVARCHAR (24) NOT NULL,
	SODT INT UNIQUE,
	DIACHI NVARCHAR (100)
);
CREATE TABLE NHANVIEN(
	MANV INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
	TENNV NVARCHAR (24) NOT NULL,
	TENDANGNHAP VARCHAR (21) NOT NULL UNIQUE,
	MATKHAU VARCHAR (15) NOT NULL,
);
CREATE TABLE SANPHAM(
	MASP CHAR (8) NOT NULL PRIMARY KEY,
	TENSP NVARCHAR (21) NOT NULL,
	LOAISP NVARCHAR (21) NOT NULL,
	HINHSP NVARCHAR(100) NOT NULL,
	GIA MONEY NOT NULL,
	SOLUONG INT NOT NULL,
);
CREATE TABLE HOADON(
	MAHD CHAR (8) NOT NULL PRIMARY KEY,
	MANV INT NOT NULL FOREIGN KEY REFERENCES NHANVIEN(MANV),
	MAKH VARCHAR(8) NOT NULL FOREIGN KEY REFERENCES KHACHHANG(MAKH),
	NGAYTAO DATETIME NOT NULL,
);

CREATE TABLE CHITIETHOADON (
	MAHD CHAR(8) NOT NULL FOREIGN KEY REFERENCES HOADON (MAHD),
	MASP CHAR(8) NOT NULL FOREIGN KEY REFERENCES SANPHAM(MASP),
	SOLUONG INT NOT NULL,
	DONGIA FLOAT NOT NULL,
	THANHTIEN FLOAT NOT NULL,
);

ALTER TABLE NHANVIEN ALTER COLUMN MATKHAU VARCHAR (15) NOT NULL
DROP TABLE CHITIETHOADON
DROP TABLE HOADON
DROP TABLE KHACHHANG
DROP TABLE NHANVIEN
DROP TABLE SANPHAM

SELECT TENDANGNHAP , MATKHAU
FROM NHANVIEN
WHERE TENDANGNHAP = 'lamlong70'