CREATE DATABASE QUANLYDOANHTHUDA;
DROP DATABASE QUANLYDOANHTHUDA;
CREATE TABLE KHACHHANG(
	MAKH VARCHAR(8) NOT NULL PRIMARY KEY,
	TENKH NVARCHAR (24) NOT NULL,
	SODT INT UNIQUE,
	DIACHI NVARCHAR (100)
);
CREATE TABLE NHANVIEN(
	MANV INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
	TENNV NVARCHAR (24) NOT NULL,
	MACHUCVU CHAR (10) FOREIGN KEY REFERENCES CHUCVU(MACHUCVU), 
	MABOPHAN CHAR (10) FOREIGN KEY REFERENCES BOPHAN(MABOPHAN),
	NGAYSINH DATETIME,
	NGAYVAOLAM DATETIME,
	DIENTHOAI INT,
	GIOITINH CHAR (5),
	DIACHI NVARCHAR(100),
	TENDANGNHAP VARCHAR (21) NOT NULL UNIQUE,
	MATKHAU VARCHAR (15) NOT NULL,
);
CREATE TABLE LUONG(
	MANV INT NOT NULL FOREIGN KEY REFERENCES NHANVIEN(MANV),
	LUONGCOBAN MONEY NOT NULL,
	PHUCAP MONEY  NOT NULL
);
CREATE TABLE CHUCVU(
	MACHUCVU CHAR(10) PRIMARY KEY,
	TENCHUCVU NVARCHAR(24)
);
CREATE TABLE BOPHAN(
	MABOPHAN CHAR(10) PRIMARY KEY,
	TENBOPHAN NVARCHAR(24)
);
CREATE TABLE SANPHAM(
	MASP CHAR (8) NOT NULL PRIMARY KEY,
	TENSP NVARCHAR (21) NOT NULL,
	LOAISP NVARCHAR (21) NOT NULL,
	NGAYNHAP DATETIME,
	GIA MONEY NOT NULL,
	SOLUONG INT NOT NULL,
);
CREATE TABLE HOADON(
	MAHD CHAR (8) NOT NULL PRIMARY KEY,
	MANV INT NOT NULL FOREIGN KEY REFERENCES NHANVIEN(MANV),
	MAKH VARCHAR(8) NOT NULL FOREIGN KEY REFERENCES KHACHHANG(MAKH),
	NGAYTAO DATETIME NOT NULL,
);

CREATE TABLE CHITIETHOADON (
	MAHD CHAR(8) NOT NULL FOREIGN KEY REFERENCES HOADON (MAHD),
	MASP CHAR(8) NOT NULL FOREIGN KEY REFERENCES SANPHAM(MASP),
	SOLUONG INT NOT NULL,
	DONGIA FLOAT NOT NULL,
	THANHTIEN FLOAT NOT NULL,
);

select TENDANGNHAP
from NHANVIEN
where TENNV=N'Lâm Thành Long'